### ISSUE TITLE
Trace (possible) memory leak

### ISSUE THREAD

**Issue by schlusslicht** [cceh/kosh#111]
When running kosh instances long-term, their memory.usage grows significantly, which indicates a memory leak. Most probable this leak originates in the XML-parsing components of kosh, possibly occurring because of the use of threads.

This needs to be traced by, e.g., using valagrind in combination with `PYTHONMALLOC=malloc`.

**Comment by vocabulista** [comment]
Fixed with commit d9756497cec3b649fabc16523ad2dd8e7f63cc1f
