### ISSUE TITLE
Add title and authors

### ISSUE THREAD

**Issue by vocabulista** [cceh/kosh#112]
We should implement a xpath property or a custom field within the JSON mappings to assign a human understandable name to any imported/served dictionary. Also information about its authors. 

E.g.:
```json
{
  "mappings": {
    "_meta": {

    "title": "My Nicename", // <--
    "authors": ["Peter Pan", "Wendy"],   // <--

      "_xpaths": {

        "title": "//title", // <--

        "id": "./@xml:id",
        "root": "//tei:cit[@type='item']",
        "fields": {
          ...
        }
      }
    },
    "properties": {
      ...
    }
  }
}
```

**Comment by schlusslicht** [comment]
Closed by f4b2e254ebadbdfa483bcf8cc7b391a2e75c4cd1 (and 00036698f74b5ed435c996223cd79525b500edd6)
