### ISSUE TITLE
make command mentioned in docs for native backend deployment

### ISSUE THREAD

**Issue by Querela** [cceh/kosh#124]
On page [Deploying Kosh's Backend > On Unix-like Systems](https://kosh-docs.vercel.app/deployment/backend#on-unix-like-systems) step 3 mentions a `make` command (_Build Kosh using the make command_). This should be something old since I saw no `Makefile` in the repo. Or is this dependent on something else?

**Comment by schlusslicht** [comment]
Thank You for bringing this to our attention! As to why this is mentioned in the docs: The [`Makefile`](https://github.com/cceh/kosh/blob/5db75db631a7f52491000511f531e1121a8ceee6/Makefile), along with the [`setup.py`](https://github.com/cceh/kosh/blob/5db75db631a7f52491000511f531e1121a8ceee6/setup.py) and a [`requirements.txt`](https://github.com/cceh/kosh/blob/5db75db631a7f52491000511f531e1121a8ceee6/requirements.txt) were dropped a couple of months ago (as part of 129c07f5b7699296a25b6e13a78c0a7892efe14c) in favour of the new [`pyproject.toml`](https://github.com/cceh/kosh/blob/master/pyproject.toml) "paradigm".

As this is a docs-specific issue, I'll assign @vocabulista to look into it.
