### ISSUE TITLE
Support for python 3.8+?

### ISSUE THREAD

**Issue by Querela** [cceh/kosh#125]
I think you could relax the python version requirement from `3.11` down to `3.8`. Is there a reason to not support older python versions due to new syntax usage? Locally, I could run `kosh` with `3.8` but I have not yet tested all possible code paths just some random api requests.

**Comment by schlusslicht** [comment]
As far as I remember there was a reason. But it might just have been that I've eagerly updated to the latest [`python:alpine` Docker Image](https://github.com/cceh/kosh/blame/master/Dockerfile#L1) and just synced the required python version within the `pyproject.toml`. And, as You mentioned, `kosh` runs fine under `3.8` (just tested this). I'll try to have a deeper look into this issue in the coming days. Again, thank You for bringing this to our attention.
